calculator/Models/ErrorViewModel.cs
using System;

namespace calculator.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

calculator/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using calculator.Models;

namespace calculator.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

calculator/Controllers/calculatorController.cs
using Microsoft.AspNetCore.Mvc;

namespace calculator.Controllers
{
    public class calculatorController : Controller
    {
        public IActionResult calculator()
        {
            return View();
        }
    }

}

calculator/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

calculator/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - calculator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/s.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Main</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="calculator" asp-action="calculator">calculator</a>
                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - calculator - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="~/js/calculator.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

calculator/Views/calculator/calculator.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<input class="screen "  id="screen">
<button class="number" id = "num "  value  = "0" type="button" >0</button>
<button class="number" type="button" value  = "1" >1</button>
<button class="number" type="button" value  = "2"  >2</button>
<button class="number" type="button" value  = "3"  >3</button>
<button class="number" type="button" value  = "4"  >4</button>
<button class="number" type="button" value  = "5"  >5</button>
<button class="number" type="button" value  = "6"  >6</button>
<button class="number" type="button" value  = "7"  >7</button>
<button class="number" type="button" value  = "8"  >8</button>
<button class="number" type="button" value  = "9"  >9</button>
<button class="number" type="button" value  = "."  >.</button>
<button class="operator" id = "sum" value  = "+" type="button')">+</button>
<button class="operator" id = "minus" value  = "-" type="button')">-</button>
<button class="operator" id = "gang" value  = "*" type="button')">*</button>
<button class="operator" id =  "delling" value  = "/" type="button')">/</button>
<button class="equal" id =  "equal"  type="button')">=</button>
<button class="c" id = "c" type="button')">C</button>
<button class="ce" id = "ce" type="button')">CE</button>